// <auto-generated />
namespace ninja_challenge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CambioModelo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambioModelo));
        
        string IMigrationMetadata.Id
        {
            get { return "202310062144236_CambioModelo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
